### PR TITLE
chore: Bump Flask to 2.3.3 and update dependencies

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Updates Flask to 2.3.3
- Update other requirements where needed to be compatible

## QA

- I have set up demo on u.com. Check that the packages provided by Flask-Base are working:
https://ubuntu-com-14024.demos.haus/

### CODE REVIEW

**Comment by carkod** [comment]
Can you bump the version of flask-base? if you don't do it won't automatically trigger a renovate PR

**Comment by petesfrench** [comment]
@samhotep Any idea why these checks are hanging?

**Comment by petesfrench** [comment]
@carkod Can you take another look please

**Comment by carkod** [comment]
> @samhotep Any idea why these checks are hanging?

Try updating the labels.

**Review by carkod — APPROVED** [review]

**Comment by samhotep** [comment]
As @carkod suggested I've updated the versions, but the checks are borked now - taking a look

**Comment by samhotep** [comment]
@petesfrench checks are running, you're good to merge :)

**Pull request merged**
